// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4pux6S7IgsvKt5HM2kyWl0e6Gkm8meYQ',
    appId: '1:780230442237:web:b1d84cbf67441c8b855294',
    messagingSenderId: '780230442237',
    projectId: 'agrishieldapp-45646',
    authDomain: 'agrishieldapp-45646.firebaseapp.com',
    storageBucket: 'agrishieldapp-45646.firebasestorage.app',
    measurementId: 'G-8W2HD6GFF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHctGyZynonJMEQ78cNRhrj2YwhGBLNJo',
    appId: '1:780230442237:android:126353888b5c71ad855294',
    messagingSenderId: '780230442237',
    projectId: 'agrishieldapp-45646',
    storageBucket: 'agrishieldapp-45646.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxTw_Ni9nR-W2qBZNUFmfHrhnZVv4rZ44',
    appId: '1:780230442237:ios:70bbaad73cdd1953855294',
    messagingSenderId: '780230442237',
    projectId: 'agrishieldapp-45646',
    storageBucket: 'agrishieldapp-45646.firebasestorage.app',
    iosBundleId: 'com.example.agrishieldApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxTw_Ni9nR-W2qBZNUFmfHrhnZVv4rZ44',
    appId: '1:780230442237:ios:70bbaad73cdd1953855294',
    messagingSenderId: '780230442237',
    projectId: 'agrishieldapp-45646',
    storageBucket: 'agrishieldapp-45646.firebasestorage.app',
    iosBundleId: 'com.example.agrishieldApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4pux6S7IgsvKt5HM2kyWl0e6Gkm8meYQ',
    appId: '1:780230442237:web:71977caaae896f4a855294',
    messagingSenderId: '780230442237',
    projectId: 'agrishieldapp-45646',
    authDomain: 'agrishieldapp-45646.firebaseapp.com',
    storageBucket: 'agrishieldapp-45646.firebasestorage.app',
    measurementId: 'G-WHQF4NCQMG',
  );

}